### ISSUE TITLE
alarm settings back button

### ISSUE THREAD

**Issue by cicardia** [andrefbsantos/boilr#82] opened 2015-02-25 03:56 UTC
we've discussed this, but joel noticed that when editing an alarm's settings, you have to use android's back button to go back to the alarm list. I know why we don't have one. because it makes no difference to the app if you push the back or wtv button, but would it be possible to have the exact same "alarm list" button on the settings page regardless of being the 1st or wtv time your mingling with the alarm's settings?

**Comment by dllud** [comment] 2015-02-25 04:23
Duplicate of  #38

**Closed by dllud** 2015-02-25 04:23 UTC
Labels: duplicate, enhancement

**Comment by cicardia** [comment] 2015-02-25 23:41
i looked for it but couldn't find it. my bad!
